version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/finance
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./data:/data

  frontend:
    build: ./frontend
    ports:
      - "8050:8050"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

